class Autogenerated {
  int? active;
 

  Autogenerated({
    required this.active,
   
  });

  factory Autogenerated.fromJson(Map<String, dynamic> json) {
    return Autogenerated(
      active: json['active'],
     
    );
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = {};
    data['active'] = active;
   
    return data;
  }
}
