// ignore_for_file: avoid_print

import 'dart:convert';

import 'package:google_generative_ai/google_generative_ai.dart';
import 'package:job_circle/src/model/user_profile/user_model.dart';

class ResumeAiService {
  final model = GenerativeModel(
    model: "gemini-2.5-flash", // ✅ NEW (Faster & Free Tier available)
    apiKey: 'AIzaSyAnhaXULIUPpgeewuV7_bFZBhZBPL1PLBc',
  );

  Future<Map<String, dynamic>> polishResumeData(ProfileModel rawProfile) async {
    // 1. Construct the Prompt
    final prompt =
        '''
      You are an expert HR Resume Writer. I will give you a candidate's raw profile data in JSON.
      Your task:
      1. Rewrite the "experience" descriptions to be result-oriented (use Action Verbs).
      2. Write a professional "Profile Summary" (about 50 words) based on skills.
      3. Fix any grammar issues.
      4. Return ONLY valid JSON output matching the structure. Do not use Markdown or code blocks.
      5. If any field is missing, leave it empty in the JSON.
      6. Do change any field names or structure as per you.
      7. Do make sure that resume should be recruiter friendly.
      
      Raw Data: ${jsonEncode(rawProfile)}
      
      Expected JSON Structure:
      {
        "fullName": "String",
        "summary": "String (Generated by you)",
        "email": "String",
        "phone": "String",
        "location": "String",
        "languages": ["String"],
        "skills": ["String"],
        "experience": [
          {
            "company": "String",
            "role": "String",
            "duration": "String",
            "description": "String (Polished by you)"
          }
        ]
        "education": [
          {
            "institution": "String",
            "degree": "String",
            "fieldOfStudy": "String",
            "startDate": "String",
            "endDate": "String"
          }
        ],
        "certifications": [
          {
            "name": "String",
            "issuingOrganization": "String",
            "issueDate": "String",
            "expirationDate": "String"
          }
        ],
        "projects": [
          {
            "title": "String",
            "description": "String",
            "link": "String"
          }
        ],
       
      }
    ''';

    try {
      // 2. Call Gemini
      final content = [Content.text(prompt)];
      final response = await model.generateContent(content);

      // 3. Clean and Parse Response
      String responseText = response.text ?? "{}";

      // Remove any markdown ```json if Gemini adds it
      responseText = responseText
          .replaceAll('```json', '')
          .replaceAll('```', '');

      return jsonDecode(responseText);
    } catch (e) {
      print("AI Error: $e");
      // Fallback: Return raw data if AI fails
      return {
        "fullName":
            "${rawProfile.firstName ?? ''} ${rawProfile.lastName ?? ''}",
        "summary": rawProfile.bio ?? '',
        "email": rawProfile.gmail ?? '',
        "phone": rawProfile.mobile ?? '',
        "location": rawProfile.userFullLocation ?? '',
        "languages": rawProfile.languagesKnown ?? [],
        "skills": rawProfile.allSkills ?? [],
        "experience":
            rawProfile.experiences
                ?.map(
                  (exp) => {
                    "company": exp.companyName ?? '',
                    "role": exp.jobTitle ?? '',
                    "duration":
                        "${exp.joiningDate ?? ''} - ${exp.lastWorkingDate ?? ''}",
                    "description": exp.jobRole ?? '',
                  },
                )
                .toList() ??
            [],
        "education":
            rawProfile.educationDetails
                ?.map(
                  (edu) => {
                    "institution": edu.schoolOrCollegeName ?? '',
                    "degree": edu.degreeSpc ?? '',
                    "fieldOfStudy": edu.fieldOfStudy ?? '',
                    "startDate": edu.firstYear ?? '',
                    "endDate": edu.passingYear ?? '',
                  },
                )
                .toList() ??
            [],
        "certifications":
            rawProfile.certifications
                ?.map(
                  (cert) => {
                    "name": cert.certificationName ?? '',
                    "issuingOrganization": cert.issuingOrganization ?? '',
                    "issueDate": cert.issueDate ?? '',
                    "expirationDate": cert.expirationDate ?? '',
                  },
                )
                .toList() ??
            [],
        "projects":
            rawProfile.projects
                ?.map(
                  (proj) => {
                    "title": proj.projectTitle ?? '',
                    "description": proj.description ?? '',
                    "link": proj.url ?? '',
                  },
                )
                .toList() ??
            [],
      };
    }
  }
}
